import assert from 'node:assert/strict';
import Core from './core.bend';

const list = xs => xs.reduceRight((tail, head) => ({ $: 'Con', head, tail }), { $: 'Nil' });
const suffix = pattern => ({ $: 'Suffix', label: 'fixture', pattern });
const name = pattern => ({ $: 'Name', label: 'fixture', pattern });
const paths = list(['README.md', 'go.mod', 'src/main.go', 'src/main_test.go', 'web/package.json', 'web/app.tsx']);
assert.equal(Core.files(paths), 6n);
assert.equal(Core.count(paths, suffix('.go')), 2n);
assert.equal(Core.count(paths, suffix('.ts')), 0n);
assert.equal(Core.count(paths, name('package.json')), 1n);
assert.equal(Core.matches(name('go.mod'), 'notgo.mod'), false);
assert.equal(Core.matches(suffix('.go'), 'main.go.bak'), false);
assert.equal(Core.matches(suffix('.go'), 'MAIN.GO'), false);
assert.equal(Core.count(list([]), suffix('.go')), 0n);
const report = Core.report(paths);
assert.match(report, /Files inventoried: 6/);
assert.match(report, /\| Go \| 2 \| src\/main.go<br>src\/main&#95;test.go<br>/);
assert.match(report, /\| npm-compatible \| 1 \| web\/package.json<br>/);
assert.match(report, /\| Go test files \| 1/);
assert.doesNotMatch(report, /\| Python \|/);
assert.match(Core.report(list([])), /Files inventoried: 0/);
const many = Core.report(list(['a.go', 'b.go', 'c.go', 'd.go']));
assert.match(many, /\| Go \| 4 \| a.go<br>b.go<br>c.go<br>/);
assert.doesNotMatch(many, /d.go/);
assert.equal(Core.escape('<img>|&.go'), '&lt;img&gt;&#124;&amp;.go');
assert.equal(Core.escape('[click](x)*`_.go'), '&#91;click&#93;(x)&#42;&#96;&#95;.go');
assert.equal(Core.report(paths), report);
console.log('Core assertions passed.');
